server:
  port: 8001

spring:
  # 数据源配置
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    #    fasle 表示不向注册中心注册自己
    register-with-eureka: true
    #    false表示自己就是注册中心
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

