server:
  port: 7002

eureka:
  instance:
    hostname: localhost
  client:
#    fasle 表示不向注册中心注册自己
    register-with-eureka: false
#    false表示自己就是注册中心
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/