server:
  port: 8000


eureka:
  client:
    #    fasle 表示不向注册中心注册自己
    register-with-eureka: true
    #    false表示自己就是注册中心
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

ribbon:
  #  指的是建立连接所用的时间，适用于网络正常的情况下，两端连接所用的时间
  ReadTimeout: 60000
  #  指的是建立连接后从服务器读取到可用的资源所用的时间
  ConnectTimeout: 60000

#  监控接口日志打印
logging:
  level:
    com.thd.springcloud.service.*: debug