server:
  port: 8401

spring:
  # 数据源配置
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.65.28:8848
    sentinel:
      transport:
        dashboard: 192.168.65.28:8080
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'

