server:
  port: 2001


spring:
  # 数据源配置
  application:
    name: seta-order-service
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.65.28:8848/

  datasource:
    url: jdbc:mysql://192.168.65.105:3306/seta_order?autoReconnect=true&roundRobinLoadBalance=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 初始化大小，最小，最大
    initial-size: 5
    max-active: 10
    min-idle: 5
    # 配置获取连接等待超时的时间
    max-wait: 6000


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tdh.springcloud.setaorderservice2001.entitys


feign:
  hystrix:
    enabled: false